CREATE TABLESPACE coordinadora
DATAFILE 'coordinadora001' SIZE 3G;

CREATE UNDO TABLESPACE undo_coordinadora
DATAFILE 'undo_coordinadora001' SIZE 100M;

CREATE BIGFILE TABLESPACE big_coordinadora
DATAFILE 'bigF_coordinadora001' SIZE 4G;

select * from  dba_tablespaces;
select * from  dba_data_files;


CREATE USER amartinezg
IDENTIFIED BY  amartinezg
DEFAULT TABLESPACE coordinadora
QUOTA UNLIMITED on coordinadora;

GRANT dba TO amartinezg;

GRANT CREATE SESSION TO amartinezg;

CREATE PROFILE clerk LIMIT
PASSWORD_LIFE_TIME 40
SESSIONS_PER_USER 1
IDLE_TIME 15
FAILED_LOGIN_ATTEMPTS 3;

CREATE PROFILE development LIMIT
PASSWORD_LIFE_TIME 100
SESSIONS_PER_USER 2
IDLE_TIME 30;
FAILED_LOGIN_ATTEMPTS 0;

CREATE PROFILE operative  LIMIT
PASSWORD_LIFE_TIME 30
SESSIONS_PER_USER 1
IDLE_TIME 5
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_REUSE_TIME 30
PASSWORD_REUSE_MAX 3;

CREATE USER estefah
IDENTIFIED BY  estefah
DEFAULT TABLESPACE coordinadora;

CREATE USER erikab
IDENTIFIED BY  erikab
DEFAULT TABLESPACE coordinadora;

CREATE USER andresm
IDENTIFIED BY  andresm
DEFAULT TABLESPACE coordinadora;


GRANT CREATE SESSION TO andresm;

GRANT CREATE SESSION TO erikab;

GRANT CREATE SESSION TO estefah;


Alter user estefah profile clerk;

Alter user erikab profile development;

Alter user andresm profile operative;

ALTER USER andresm ACCOUNT LOCK;

